# Generated by Django 5.0.2 on 2024-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lastseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastseen',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
