# Generated by Django 5.0.2 on 2024-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friend',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='me',
            field=models.EmailField(max_length=254),
        ),
    ]
