# Generated by Django 5.0.2 on 2024-03-07 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
