# Generated by Django 5.0.2 on 2024-03-07 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_contact_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='me', to=settings.AUTH_USER_MODEL),
        ),
    ]
