# Generated by Django 5.0.2 on 2024-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_message_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
