# Generated by Django 5.0.2 on 2024-03-11 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_message_email_message_receiver_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
